"""初始資料表：架構書 §7 的 14 張資料表（spec 0005）

Revision ID: 0001
Revises:
Create Date: 2026-10-01 01:28:47.555765
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# 互相參照的外鍵：所有資料表建立後再加上，降版時先移除
DEFERRED_FKS = (
    ("fk_characters_locked_version_id", "characters", "character_versions", "locked_version_id"),
    ("fk_videos_selected_plan_id", "videos", "plans", "selected_plan_id"),
    ("fk_shots_current_take_id", "shots", "shot_takes", "current_take_id"),
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "projects",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("output_defaults", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "brand_profiles",
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("visual", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("selling_points", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tone", sa.Text(), nullable=False),
        sa.Column("info", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("sources", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("project_id"),
    )
    op.create_table(
        "characters",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("locked_version_id", sa.String(length=36), nullable=True),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_characters_project_id"), "characters", ["project_id"], unique=False)
    op.create_table(
        "scene_photos",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("image_key", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_scene_photos_project_id"), "scene_photos", ["project_id"], unique=False)
    op.create_table(
        "videos",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("mode", sa.String(), nullable=False),
        sa.Column("topic", sa.Text(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("status_history", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("selected_plan_id", sa.String(length=36), nullable=True),
        sa.Column("cost_cap", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("timeline", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_videos_project_id"), "videos", ["project_id"], unique=False)
    op.create_table(
        "approvals",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("video_id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("input_hash", sa.String(), nullable=False),
        sa.Column("cost_cap", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("auto_approved", sa.Boolean(), nullable=False),
        sa.Column("approved_by", sa.String(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["video_id"], ["videos.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_approvals_video_id"), "approvals", ["video_id"], unique=False)
    op.create_table(
        "character_versions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("character_id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("identity_board_key", sa.String(), nullable=True),
        sa.Column("cutout_key", sa.String(), nullable=True),
        sa.Column("anchor_card", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("voice", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["character_id"], ["characters.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("character_id", "version"),
    )
    op.create_table(
        "cost_entries",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("video_id", sa.String(length=36), nullable=False),
        sa.Column("job_id", sa.String(), nullable=False),
        sa.Column("credits", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["video_id"], ["videos.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_cost_entries_video_id"), "cost_entries", ["video_id"], unique=False)
    op.create_table(
        "plans",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("video_id", sa.String(length=36), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("engine", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["video_id"], ["videos.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_plans_video_id"), "plans", ["video_id"], unique=False)
    op.create_table(
        "renders",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("video_id", sa.String(length=36), nullable=False),
        sa.Column("aspect_ratio", sa.String(), nullable=False),
        sa.Column("subtitle_lang", sa.String(), nullable=True),
        sa.Column("mp4_key", sa.String(), nullable=False),
        sa.Column("thumb_key", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["video_id"], ["videos.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_renders_video_id"), "renders", ["video_id"], unique=False)
    op.create_table(
        "shots",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("video_id", sa.String(length=36), nullable=False),
        sa.Column("shot_no", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("duration_s", sa.Float(), nullable=False),
        sa.Column("scene_photo_id", sa.String(length=36), nullable=True),
        sa.Column("placement", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("prompt", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("current_take_id", sa.String(length=36), nullable=True),
        sa.ForeignKeyConstraint(["scene_photo_id"], ["scene_photos.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["video_id"], ["videos.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("video_id", "shot_no"),
    )
    op.create_table(
        "shot_takes",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("shot_id", sa.String(length=36), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("keyframe_key", sa.String(), nullable=True),
        sa.Column("clip_key", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["shot_id"], ["shots.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("shot_id", "attempt"),
    )
    op.create_table(
        "generation_jobs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("shot_take_id", sa.String(length=36), nullable=False),
        sa.Column("idempotency_key", sa.String(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column("external_id", sa.String(), nullable=True),
        sa.Column("provider_idempotency_key", sa.String(), nullable=True),
        sa.Column("input_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("input_hash", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("est_cost", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("actual_cost", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["shot_take_id"], ["shot_takes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_index(
        op.f("ix_generation_jobs_shot_take_id"), "generation_jobs", ["shot_take_id"], unique=False
    )
    for name, source, target, column in DEFERRED_FKS:
        op.create_foreign_key(name, source, target, [column], ["id"], ondelete="SET NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    for name, source, _, _ in DEFERRED_FKS:
        op.drop_constraint(name, source, type_="foreignkey")
    op.drop_index(op.f("ix_generation_jobs_shot_take_id"), table_name="generation_jobs")
    op.drop_table("generation_jobs")
    op.drop_table("shot_takes")
    op.drop_table("shots")
    op.drop_index(op.f("ix_renders_video_id"), table_name="renders")
    op.drop_table("renders")
    op.drop_index(op.f("ix_plans_video_id"), table_name="plans")
    op.drop_table("plans")
    op.drop_index(op.f("ix_cost_entries_video_id"), table_name="cost_entries")
    op.drop_table("cost_entries")
    op.drop_table("character_versions")
    op.drop_index(op.f("ix_approvals_video_id"), table_name="approvals")
    op.drop_table("approvals")
    op.drop_index(op.f("ix_videos_project_id"), table_name="videos")
    op.drop_table("videos")
    op.drop_index(op.f("ix_scene_photos_project_id"), table_name="scene_photos")
    op.drop_table("scene_photos")
    op.drop_index(op.f("ix_characters_project_id"), table_name="characters")
    op.drop_table("characters")
    op.drop_table("brand_profiles")
    op.drop_table("projects")
    op.drop_table("users")
    # ### end Alembic commands ###
